language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libqt5webkit5-dev
            - qtdeclarative5-dev
            - libmpfr-dev
      env:
        - SET_COMPILER="CC=gcc-5 && CXX=g++-5"
        - SET_QMAKE="QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake"

    - os: osx
      osx_image: xcode8
      env:
        - SET_COMPILER="brew update && brew install gcc && env CC=gcc-7 && env CXX=g++-7"
        - SET_QMAKE="brew update && brew install qt && env QMAKE=/usr/local/opt/qt/bin/qmake"

before_script:
  - eval "${SET_COMPILER}"
  - eval "${SET_QMAKE}"

script:
  - qmake -qt=qt5 -r P4.pro
  - make
