language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libqt5webkit5-dev
            - qtdeclarative5-dev
            - libmpfr-dev
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 && QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake"
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew update && brew install gcc && brew install qt && CC=gcc-7 && CXX=g++-7"

before_script:
  - eval "${MATRIX_EVAL}"

script:
  - qmake -qt=qt5 -r P4.pro
  - make
